##  QUESTION1

Q1a)


In [23]:
#The Predicted Value of y_hat(x) for x = 1.
y_hat= round(0.4 + 0.8*(1),2)
y_true = 1
y_hat
# The error for when x=1
error = round(0.5 * (y_hat - y_true)**2,2)

#print the y_hat and error
print("y_hat = ", y_hat)
print("error = ", error)

y_hat =  1.2
error =  0.02


Q1b)

In [22]:
#The Predicted Value of y_hat(x) for x = 2.
y_hat= 0.4 + 0.8*(2)
y_true = 3
y_hat

# The error for when x=2
error = round(0.5 * (y_hat - y_true)**2,2)

#print the y_hat and error
print("y_hat = ", y_hat)
print("error = ", error)

y_hat =  2.0
error =  0.5


Q1c)

In [26]:
#sum of squares error for this model

def y_hat(x):
    y = 0.4 + 0.8*(x)
    return y

# x values
x_values = [1,2,3,4,5]
# y avlues
y_values = [1,3,2,3,5]
y_predicted = []
error = 0.0
for x in x_values:
    y_predicted.append(round(y_hat(x),2))

for i in range(len(y_values)):
    error += 0.5 * (y_values[i] - y_predicted[i])**2

error = round(error, 2)
error

1.2

## QUESTION 4

Q4a)

In [3]:
import numpy as np

mu=0
std=10
mean=150

#i
sample = np.random.normal(0,10,150)

#ii
def designMatrix(s, rows, cols):
    design = np.ones((rows, cols))
    for i in range(cols):
        design[:,i] = s**i
    return design

design = designMatrix(sample, 150, 3)
print(design)
#design
      

[[ 1.00000000e+00  1.66270574e+00  2.76459039e+00]
 [ 1.00000000e+00 -1.62956770e+01  2.65549090e+02]
 [ 1.00000000e+00  9.06033847e+00  8.20897331e+01]
 [ 1.00000000e+00 -1.38014892e+01  1.90481105e+02]
 [ 1.00000000e+00 -1.80859568e+01  3.27101833e+02]
 [ 1.00000000e+00 -7.73452013e+00  5.98228017e+01]
 [ 1.00000000e+00 -1.80724841e+00  3.26614680e+00]
 [ 1.00000000e+00 -3.30964768e-01  1.09537678e-01]
 [ 1.00000000e+00 -5.64487669e+00  3.18646328e+01]
 [ 1.00000000e+00 -1.42472286e+01  2.02983522e+02]
 [ 1.00000000e+00 -1.33071712e+01  1.77080807e+02]
 [ 1.00000000e+00 -1.58855542e+01  2.52350832e+02]
 [ 1.00000000e+00  2.24611724e+00  5.04504266e+00]
 [ 1.00000000e+00  1.58971966e+01  2.52720859e+02]
 [ 1.00000000e+00  5.49887879e+00  3.02376679e+01]
 [ 1.00000000e+00 -2.44974836e+00  6.00126704e+00]
 [ 1.00000000e+00 -9.91636581e+00  9.83343110e+01]
 [ 1.00000000e+00  2.78640620e+00  7.76405949e+00]
 [ 1.00000000e+00 -1.36046482e+01  1.85086454e+02]
 [ 1.00000000e+00 -6.93494072e+

In [ ]:
theta=np.random.uniform(0,1,size=3)
th0=theta[0]
th1=theta[1]
th2=theta[2]